# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Evant' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Evant
  pod 'AppCenter/Crashes', '~> 1.3.0'
  pod 'AppCenter/Analytics', '~> 1.3.0'
  pod 'AppCenterReactNativeShared', '~> 1.2.0'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'EvantTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Evant-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Evant-tvOS

  target 'Evant-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
